export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const CLEAR_CART = "CLEAR_CART";
export const LOAD_CURRENT_ITEM = "LOAD_CURRENT_ITEM";
export const ADD_JUST_ITEM_QTY = "ADD_JUST_ITEM_QTY"